skylark-platform/skylark-ui

src/components/select/select.component.tsx, src/pages/index.tsx
=> feat: Change link, change select component

src/components/panel/panel.component.tsx, src/components/panel/panelSections/index.tsx, src/components/panel/panelSections/panelImages.component.tsx, src/components/panel/panelSections/panelMetadata.component.tsx, src/components/tabs/tabs.component.tsx, src/interfaces/skylark/objects.ts
https://skylarkplatform.atlassian.net/browse/SL-2319
=> [SL-2319] feat: display images in the metadata panel

src/components/objectListing/objectListing.component.tsx, src/components/objectListing/table/table.component.tsx, src/components/panel/panel.component.tsx, src/components/tabs/tabs.component.tsx, src/constants/skylark.ts, src/hooks/useGetObject.ts, src/hooks/useSearch.ts, src/interfaces/skylark/objects.ts
- Refactor table styling to memoise class names + make it easier to understand
- Add experimental performance improvement (memoise table value until `getValue` changes)
- Add image to object listing
=> [SL-2342] Refactor Table styling + experimental performance improvement, add image to Object Listing

cypress/e2e/navigation.cy.ts, package.json, src/components/betaReleaseAuthModal/betaReleaseAuthModal.component.tsx, src/components/icons/fileText.component.tsx, src/components/icons/icons.stories.tsx, src/components/icons/index.tsx, src/components/navigation/links/links.component.tsx, src/components/navigation/links/links.stories.tsx, src/components/navigation/navigation/navigation.component.tsx, src/constants/skylark.ts, src/lib/graphql/skylark/client.test.ts, src/lib/graphql/skylark/client.ts, src/pages/developer/playground.tsx, src/styles/globals.css, tailwind.config.js, yarn.lock
- Adds GraphiQL Playground page targeting a users Skylark
- Refactors nav height into 2 utility classes
- Adds Developer section to navigation as a dropdown with links to the API documentation and the playground
https://skylarkplatform.atlassian.net/browse/SL-2366
=> [SL-2366] feat: Add GraphiQL Playground

src/pages/developer/playground.tsx
- Fixes the refetching the schema button following https://github.com/graphql/graphiql/issues/2799#issuecomment-1274399635
=> fix: only update fetcher when uri or token changes

.github/workflows/call-vercel-deploy-hook.yml, cypress/e2e/developer/graphiql.cy.ts, src/components/graphiqlEditor/graphiqlEditor.component.tsx, src/components/graphiqlPlayground/graphiqlPlayground.component.tsx, src/components/navigation/links/links.component.tsx, src/constants/skylark.ts, src/pages/developer/graphql-editor.tsx
- Fixes cursor moving to start while typing
- Also adds the beta environment to the Vercel Deploy Hook Workflow
https://skylarkplatform.atlassian.net/browse/SL-2427
=> [SL-2427] GraphiQL editor cursor fix

src/components/betaReleaseAuthModal/betaRelaseAuthModal.test.tsx, src/components/betaReleaseAuthModal/betaReleaseAuthModal.component.tsx, src/components/button/button.component.tsx, src/components/contentLibrary/contentLibrary.component.tsx, src/components/contentLibrary/contentLibrary.test.tsx, src/components/contentLibrary/index.tsx, src/components/objectListing/objectListing.component.tsx, src/components/objectListing/objectListing.test.tsx, src/components/objectListing/table/table.component.tsx, src/components/panel/index.tsx, src/components/panel/panel.component.tsx, src/components/panel/panel.test.tsx, src/components/panel/panelSections/panelAvailability.component.tsx, src/components/panel/panelSections/panelImages.component.tsx, src/components/panel/panelSections/panelMetadata.component.tsx, src/components/textInput/textInput.component.tsx, src/pages/index.tsx
---------
Co-authored-by: James Wallis <j@wallis.dev>
=> [SL-2391] Feature: panel pushing content library (#35)

src/components/objectListing/objectListing.component.tsx, src/styles/globals.css
Adds CSS overrides
https://skylarkplatform.atlassian.net/browse/SL-2447
=> [SL-2447] fix: add CSS override for GraphiQL Editor

.github/workflows/call-vercel-deploy-hook.yml, src/components/button/button.component.tsx, src/components/contentLibrary/contentLibrary.component.tsx, src/components/contentLibrary/contentLibrary.test.tsx, src/components/objectListing/objectListing.component.tsx, src/components/objectListing/objectListing.stories.tsx, src/components/objectListing/objectListing.test.tsx, src/components/objectListing/search/searchFilter/searchFilter.component.tsx, src/components/objectListing/table/cell/cell.component.tsx, src/components/objectListing/table/table.component.tsx, src/components/panel/panel.test.tsx, src/hooks/useGetObject.ts, src/hooks/useSearch.ts, src/lib/graphql/skylark/client.ts, src/lib/graphql/skylark/dynamicQueries.test.ts, src/lib/graphql/skylark/dynamicQueries.ts, src/pages/object/[objectType]/[uid].tsx, src/tests/fixtures/skylark/queries/search/gotPage1.json, src/tests/fixtures/skylark/queries/search/gotPage2.json
* feat: unit tests for scroll pagination
* feat: increase height of object listing table rows, detect when all search results are fetched
=> [SL-2340] feat: Infinite Loading on Search (#22)

package.json, src/components/betaReleaseAuthModal/betaReleaseAuthModal.component.tsx, src/constants/skylark.ts, src/pages/_app.tsx, yarn.lock
https://skylarkplatform.atlassian.net/browse/SL-2502
=> [SL-2502] feat: Add Plausible Analytics with custom event

src/components/panel/panelSections/panelMetadata.component.tsx, src/styles/globals.css
https://skylarkplatform.atlassian.net/browse/SL-2482
=> [SL-2482] remove word wrap on panel

src/components/graphiqlEditor/graphiqlEditor.component.tsx, src/constants/skylark.ts, src/hooks/useConnectedToSkylark.tsx, src/lib/graphql/skylark/client.ts
Adds the new `Authorization` header to the request, and keeps the old header as a beta header so that beta environments still work.
https://skylarkplatform.atlassian.net/browse/SL-2586
=> Change Auth header to Authorization

src/components/navigation/navigation/navigation.component.tsx, src/components/objectListing/objectListing.component.tsx, src/lib/graphql/skylark/dynamicQueries.ts, src/lib/skylark/parsers.ts, src/lib/utils/utils.test.ts
=> feat: parse .com urls, use vw for search input

src/components/panel/panel.component.tsx, src/components/panel/panelSections/panelContent.component.tsx, src/components/panel/panelSections/panelRelationships.component.tsx
- added message for relationship panel
- fixed adding the same object twice and then remove it
https://skylarkplatform.atlassian.net/browse/SL-2548
https://skylarkplatform.atlassian.net/browse/SL-2673
=> [SL-2548] [SL-2673] Drop same object twice and remove it

src/components/panel/panel.component.tsx, src/components/panel/panelSections/panelContent.component.tsx, src/components/panel/panelSections/panelRelationships.component.tsx
- added toast when trying to add same set to it's own content
- changed colour of trash bin to match object arrow
https://skylarkplatform.atlassian.net/browse/SL-2551
https://skylarkplatform.atlassian.net/browse/SL-2670
=> [SL-2551][SL-2670] Added toast to avoid add same set to its content

src/hooks/useConnectedToSkylark.tsx, src/lib/graphql/skylark/client.ts, src/lib/graphql/skylark/queries.ts
Disable Cache Bypass now that production is updated
=> feat: disable cache bypass

src/components/navigation/navigation/navigation.component.tsx
=> feat: Parse Customer Identifer when connect to an Int env

src/components/wysiwygEditor/wysiwygEditor.component.tsx
we don't support uploading from file
=> fix: remove quickimage

src/hooks/availability/useAvailabilityDimensionWithValues.tsx, src/hooks/availability/useAvailabilityDimensions.tsx, src/hooks/availability/useAvailabilityObjectDimensions.ts, src/hooks/objects/get/useGetObject.ts, src/hooks/objects/get/useGetObjectAvailability.tsx, src/hooks/objects/get/useGetObjectContent.tsx, src/hooks/objects/get/useGetObjectContentOf.tsx, src/hooks/objects/get/useGetObjectRelationships.ts, src/hooks/objects/update/useUpdateAvailabilityAssignedTo.tsx, src/hooks/objects/update/useUpdateAvailabilityObjectDimensions.ts, src/hooks/objects/update/useUpdateObjectAvailability.tsx, src/hooks/objects/update/useUpdateObjectContent.tsx, src/hooks/objects/update/useUpdateObjectMetadata.tsx, src/hooks/objects/update/useUpdateObjectRelationships.tsx, src/hooks/objects/useCreateObject.tsx, src/hooks/objects/useDeleteObject.tsx, src/hooks/useSearch.ts, src/hooks/useSkylarkObjectTypes.ts, src/hooks/useSkylarkSchemaIntrospection.tsx, src/hooks/useUserAccount.tsx, src/lib/graphql/skylark/client.ts
- Queries will bypass cache
- Mutations will hit cache
=> feat: only use bypass cache header on query unless overridden

cypress/e2e/contentLibrary/tabs.cy.ts, src/components/button/button.component.tsx, src/components/contentLibrary/tabbedObjectSearch/tabbedObjectSearch.component.tsx, src/components/contentLibrary/tabbedObjectSearch/tabbedObjectSearch.test.tsx, src/components/objectSearch/createButtons/createButtons.component.tsx, src/components/panel/panelSections/panelHeader.component.tsx, src/components/tabs/tabs.component.tsx
=> feat: move Create button the Content Library's tab row

src/lib/skylark/parsers.test.ts, src/lib/skylark/parsers.ts
https://skylarkplatform.atlassian.net/browse/SL-2620
=> feat: allow External ID to be nullified

src/components/contentLibrary/tabbedObjectSearch/tabbedObjectSearch.component.tsx, src/components/objectSearch/search/searchFilter/searchFilter.component.tsx, src/components/objectSearch/search/searchFilter/searchFilter.test.tsx, src/hooks/useSearchWithLookupType.tsx
=> feat: Enable look up by External ID

.prettierignore, renovate.json
=> chore: update renovate.json

cypress/e2e/contentLibrary/search.cy.ts, src/components/animatedLogo/animatedLogo.component.tsx, src/components/contentLibrary/contentLibrary.component.tsx, src/components/contentLibrary/contentLibrary.test.tsx, src/components/contentLibrary/tabbedObjectSearch/tabbedObjectSearch.component.tsx, src/components/contentLibrary/tabbedObjectSearch/tabbedObjectSearch.test.tsx, src/components/navigation/links/links.component.tsx
cause it was annoying me that it showed a blank page 
=> feat: Add animated content library logo

src/components/panel/panelSections/panelHeader.component.tsx, src/lib/graphql/skylark/dynamicMutations.ts
=> fix: don't send draft arg for Availability update

src/components/modals/graphQLQueryModal/graphQLQueryModal.component.tsx, src/components/panel/panelSections/panelContent.component.tsx, src/lib/graphql/skylark/dynamicQueries/dynamicQueries.test.ts, src/lib/graphql/skylark/dynamicQueries/getObject.ts, src/lib/graphql/skylark/dynamicQueries/getObjectGeneric.ts, src/lib/graphql/skylark/dynamicQueries/search.ts, src/lib/graphql/skylark/dynamicQueries/utils.ts
https://skylarkplatform.atlassian.net/browse/SL-2882
=> feat: refactor where UID is specified in queries, add GraphQL Query to content panel tab

src/stories/pages/404.stories.tsx
=> fix: nextjs config after storybook upgrade

src/components/contentModel/editor/contentModelEditor.component.tsx, src/components/contentModel/editor/contentModelRowInput.component.tsx, src/components/contentModel/editor/sections/common.component.tsx, src/components/contentModel/editor/sections/fields.component.tsx, src/components/contentModel/editor/sections/relationships.component.tsx, src/components/contentModel/editor/sections/uiConfig.component.tsx, src/components/objectIdentifierCard/objectIdentifier.component.tsx, src/components/pill/objectTypePill/objectTypePill.component.tsx, src/hooks/schema/update/useUpdateObjectTypeConfig.tsx
- Improves UI Config edit to be more clear + have a preview
- Splits the content model sections into files
- Adds Relationship overview
=> feat: Improve UI Config Edit

.github/workflows/cypress-tests.yml, renovate.json, src/__tests__/fixtures/skylark/queries/getObjectTypeRelationshipConfiguration/movie.json, src/__tests__/fixtures/skylark/queries/getObjectTypeRelationshipConfiguration/skylarkSet.json, src/__tests__/fixtures/skylark/queries/introspection/introspectionQuery.json, src/__tests__/mocks/handlers/introspectionHandlers.ts, src/components/contentModel/contentModel.component.tsx, src/components/contentModel/contentModel.test.tsx, src/components/contentModel/editor/contentModelEditor.component.tsx, src/components/contentModel/editor/sections/common.component.tsx, src/components/contentModel/editor/sections/fields.component.tsx, src/components/contentModel/editor/sections/relationships.component.tsx, src/components/contentModel/editor/sections/uiConfig.component.tsx, src/components/contentModel/navigation/contentModelNavigation.component.tsx, src/components/inputs/select/select.component.tsx, src/enums/graphql.ts, src/hooks/useObjectTypeRelationshipConfiguration.tsx, src/hooks/useSkylarkSchemaIntrospectionAsDataModelJSON.tsx, src/interfaces/skylark/parsedObjects.ts, src/interfaces/skylark/responses.ts, src/lib/graphql/skylark/dynamicQueries/objectsConfig.ts, src/lib/graphql/skylark/queries.ts
- Displays default sort field on content model page & data model tool 
- Fetches relationship config using a function that might not exist, so check the schema first.
https://skylarkplatform.atlassian.net/browse/SL-2906
=> feat: fetch and display relationship config

src/components/dropdown/dropdown.component.tsx, src/components/navigation/links/links.component.tsx, src/components/panel/panelSections/panelHeader.component.tsx, src/pages/object/[objectType]/[uid].tsx
- Adds a refresh button to the Panel header
- Moves open in new tab to the dropdown menu
=> feat: add button to refresh panel, move open in new tab to dropdown

src/components/panel/panelSections/panelRelationshipsSection.component.tsx
=> fix: pin relationships count displayed at 50 to 100

src/components/contentLibrary/tabbedObjectSearch/tabbedObjectSearch.component.tsx, src/components/modals/graphQLQueryModal/graphQLQueryModal.component.tsx, src/components/panel/panel.component.tsx, src/components/tabs/tabs.component.tsx, src/hooks/localStorage/useObjectSearchTabs.tsx
- Reorder object search tabs
- Fix bug where local storage doesn't update when changing active tab
https://skylarkplatform.atlassian.net/browse/SL-2823
=> feat: add ability to reorder object search tabs

src/components/button/openObjectButton.component.tsx, src/components/objectIdentifierCard/objectIdentifier.component.tsx, src/components/objectIdentifierCard/objectIdentifier.test.tsx, src/components/panel/panel.component.tsx
=> feat: when metaKey pressed, open in new tab

src/components/modals/createObjectModal/createObjectModal.component.tsx, src/components/objectIdentifierCard/objectIdentifier.component.tsx, src/components/objectIdentifierCard/objectIdentifier.test.tsx, src/components/objectSearch/objectSearch.test.tsx, src/components/objectSearch/results/grids/rows.tsx, src/components/panel/panelSections/panelHeader.component.tsx, src/lib/utils/utils.test.ts, src/lib/utils/utils.ts
=> feat: handle ctrlKey on Windows for button clicks

package.json, src/components/animatedLogo/animatedLogo.component.tsx, src/components/navigation/navigation/navigation.component.tsx, src/pages/_app.tsx, yarn.lock
=> feat: remove Christmas

src/__tests__/fixtures/skylark/queries/getObjectTypeRelationshipConfiguration/movie.json, src/__tests__/fixtures/skylark/queries/getObjectTypeRelationshipConfiguration/season.json, src/__tests__/fixtures/skylark/queries/getObjectTypeRelationshipConfiguration/skylarkSet.json, src/components/contentModel/contentModel.test.tsx, src/components/contentModel/editor/contentModelEditor.component.tsx, src/components/contentModel/editor/sections/relationships.component.tsx, src/hooks/useObjectTypeRelationshipConfiguration.tsx, src/hooks/useSkylarkSchemaIntrospectionAsDataModelJSON.tsx, src/interfaces/skylark/responses.ts, src/lib/graphql/skylark/dynamicMutations/schema.ts
Adds the toggling of `inherit_availability` to the content model page
https://skylarkplatform.atlassian.net/browse/SL-2901
=> feat: add inherit_availability changing to the content model page

src/components/inputs/radioGroup/radioGroup.component.tsx
=> fix: Radio buttons not displaying check on some devices

src/components/checkboxGrid/checkboxGrid.component.tsx
=> fix: Checkbox Grid on Safari

src/components/wysiwygEditor/wysiwygEditor.component.tsx
Allows floating the image left or right in text and adding relative URLS
=> feat: tweak tinymce config

src/components/account/status/accountStatus.component.tsx, src/components/account/status/accountStatus.stories.tsx, src/components/account/status/accountStatus.test.tsx
=> feat: add finer bg tasks count to tooltip

src/components/objectSearch/bulkObjectOptions/bulkObjectOptions.component.tsx, src/components/panel/panelSections/panelHeader.component.tsx, src/hooks/usePurgeCache.tsx, src/lib/graphql/skylark/dynamicMutations/cache.ts, src/lib/graphql/skylark/mutations.ts, src/pages/connect.tsx
=> feat: add cache purging to object panel and bulk object options

src/components/account/status/accountStatus.component.tsx, src/components/objectSearch/bulkObjectOptions/bulkObjectOptions.component.tsx, src/constants/localStorage.ts
=> feat: Purge cache only for SELF_CONFIG permissions

src/components/animatedLogo/animatedLogo.component.tsx, src/components/contentLibrary/tabbedObjectSearch/tabbedObjectSearch.component.tsx, src/components/objectSearch/objectSearch.component.tsx, src/components/panel/panel.component.tsx, src/hooks/state/usePanelObjectState.tsx
=> feat: remove useEffect

.github/workflows/cypress-tests.yml, .github/workflows/pr-checks.yml
=> feat: upgrade to node 20
