skylark-platform/skylark-ui

src/components/betaReleaseAuthModal/betaReleaseAuthModal.component.tsx
src/components/navigation/navigation/navigation.component.tsx
src/components/objectListing/objectListing.component.tsx
src/components/objectListing/table/table.component.tsx
src/components/panel/panel.test.tsx
src/components/pill/pill.component.tsx
src/constants/skylark.ts
src/pages/beta/connect.tsx
src/pages/index.tsx
src/tests/pages/beta/connect.test.tsx
tailwind.config.js

- Adds `/beta/connect` page to connect to a customer environment easily (saves copying and pasting environment info)
- Changes the `__typename` in Filters to `object type`
- Refactors object listing styling to:
- Span more of home page
- Show the end of a Pill when stickied so that its easier to identify the object type
https://skylarkplatform.atlassian.net/browse/SL-2432

[SL-2432] feat: Add connect page with redirect, refactor object listing styling

---

cypress/downloads/Episode_example.csv
cypress/e2e/import/csv.cy.ts
src/__tests__/fixtures/skylark/apiRoutes/importEpisodes.json
src/__tests__/fixtures/skylark/mutations/import/csvImportEpisodeCreationErrored.json
src/__tests__/mocks/handlers/flatfile.ts
src/__tests__/pages/api/flatfile/import.test.ts
src/interfaces/apiRoutes.ts
src/interfaces/flatfile/responses.ts
src/lib/flatfile/api/databaseView.ts
src/lib/flatfile/import.ts
src/lib/graphql/flatfile/queries.ts
src/pages/api/flatfile/import.ts
src/pages/import/csv.tsx

If imported data to Flatfile is more than 1000 rows then it will paginate the calls to the API route to get the data. This stops timeouts in API routes.
https://skylarkplatform.atlassian.net/browse/SL-2546

feat: Pagination of Flatfile data

---

src/components/contentLibrary/contentLibrary.component.tsx
src/components/objectIdentifierCard/objectIdentifier.component.tsx
src/components/objectListing/objectListing.component.tsx
src/components/objectListing/table/table.component.tsx
src/components/panel/panel.component.tsx
src/components/panel/panelSections/panelHeader.component.tsx
src/components/panel/panelSections/panelMetadata.component.tsx
src/components/panel/panelSections/panelRelationships.component.tsx
src/global.d.ts
src/styles/globals.css

Fixes a few bugs with hopefully little performance impact:
1. [SL-2598] Text panel width on Safari. Fix: Track panel size, also track when closed so we can open it back at the users specified size
2. [SL-2462] Fix text selection when dragging panel sizer on Safari. Fix: useRef to add the `select-none` className when drag start and remove onDragEnd
3. [SL-2587] `i` icon not updating it's uid's when a new search entry appears. Fix: refactor where the icons are added in the code
4. [SL-2501] Panel resizes for a second when making a new search request. Fix: Track panel size
https://skylarkplatform.atlassian.net/browse/SL-2598
https://skylarkplatform.atlassian.net/browse/SL-2462
https://skylarkplatform.atlassian.net/browse/SL-2587
https://skylarkplatform.atlassian.net/browse/SL-2501

[SL-2598,SL-2462,SL-2587,SL-2501] Content library bug fixes

---

src/lib/skylark/objects.ts
src/lib/skylark/parsers.test.ts
src/lib/skylark/parsers.ts

Fixes a required enum being parsed incorrectly as a string
https://skylarkplatform.atlassian.net/browse/SL-2675
https://skylarkplatform.atlassian.net/browse/SL-2692

feat: fix required enum being parsed as a string

---

src/components/graphiqlEditor/graphiqlEditor.component.tsx
src/constants/skylark.ts
src/hooks/useConnectedToSkylark.tsx
src/lib/graphql/skylark/client.ts

- Adds the bypass-cache header to the GraphQL Explorer
- Removes the old auth header

Bypass cache in GraphiQL

---

src/interfaces/skylark/objectOperations.ts
src/lib/skylark/objects.ts

The new `SkylarkFavoriteList` object doesn't have a list query. Need to allow `listQuery` to be undefined.

feat: handle objects without list query

---

src/components/objectSearch/results/objectSearchResults.component.tsx
src/components/objectSearch/results/table/cell/cell.component.tsx
src/components/objectSearch/results/table/columnData.tsx
src/constants/skylark.ts
src/lib/skylark/objects.ts

- Fixes object type table colours on scroll
- Removes `type` field from a default display field

feat: Fix table colours on horizontal scroll

---

.github/workflows/pr-checks.yml
src/components/contentLibrary/contentLibrary.component.tsx

Double clicking the Panel drag bar will resize it to be half of the screen. If its already half of the screen, it'll resize to the smallest width.

feat: resize panel on double click of drag bar

---

src/components/contentLibrary/contentLibrary.component.tsx
src/pages/_app.tsx

- Adds StatusPage embed so the UI shows notifications about downtime, API errors
- Improves tab switching logic to switch to relationships if an object is dragged over Playback, Images as well as Metadata UNLESS it's an Availability object being dragged in which case it switches to Availability 
https://skylarkplatform.atlassian.net/browse/SL-2751
https://skylarkplatform.atlassian.net/browse/SL-2649

feat: StatusPage embed

---

src/components/modals/createObjectModal/createObjectModal.component.tsx
src/components/modals/createObjectModal/createObjectModal.test.tsx
src/components/modals/deleteObjectModal/deleteObjectModal.component.tsx
src/components/modals/deleteObjectModal/deleteObjectModal.test.tsx
src/components/panel/panel.component.tsx
src/components/panel/panel.test.tsx
src/components/toast/toast.component.tsx
src/constants/skylark.ts
src/lib/skylark/availability/availability.ts
src/lib/skylark/parsers.test.ts
src/lib/skylark/parsers.ts

- Makes Error Toast more generic
- Refactors the values sent to GraphQL from a form

refactor: Generic GraphQL Errors Toast, modify GraphQL request field parser 

---

cypress/e2e/auth.cy.ts
cypress/e2e/contentLibrary/createObjectModal.cy.ts
cypress/e2e/contentLibrary/objectPanel.cy.ts
cypress/e2e/contentLibrary/search.cy.ts
cypress/e2e/import/csv.cy.ts
cypress/e2e/navigation.cy.ts
cypress/e2e/objectPage.cy.ts
src/components/button/button.stories.tsx
src/components/copyToClipboard/copyToClipboard.component.tsx
src/components/icons/index.tsx
src/components/icons/reactIconWrappers.tsx
src/components/inputs/availabilityPicker/availabilityPicker.component.tsx
src/components/inputs/checkbox/checkbox.component.tsx
src/components/inputs/select/select.component.tsx
src/components/modals/betaReleaseAuthModal/betaReleaseAuthModal.component.tsx
src/components/modals/createObjectModal/createObjectModal.component.tsx
src/components/modals/deleteObjectModal/deleteObjectModal.component.tsx
src/components/modals/graphQLQueryModal/graphQLQueryModal.component.tsx
src/components/modals/searchObjectsModal/searchObjectsModal.component.tsx
src/components/navigation/hamburger/hamburger.component.tsx
src/components/navigation/search/search.component.tsx
src/components/objectSearch/search/searchInput/searchInput.component.tsx
src/components/panel/panelLoading/panelLoading.component.tsx
src/components/panel/panelSections/panelHeader.component.tsx

- Reduces the number of Percy screenshots taken in Cypress tests as we're moving to the free tier
- Move icons to use the Feather Icon set so that we have more consistency

refactor: minimise Percy snapshots for free tier, use Feather Icon set

---

jest.setup.js
src/components/contentLibrary/contentLibrary.component.tsx
src/components/contentLibrary/contentLibrary.test.tsx
src/components/contentLibrary/tabbedObjectSearch/tabbedObjectSearch.component.tsx
src/components/contentLibrary/tabbedObjectSearch/tabbedObjectSearch.test.tsx
src/components/inputs/select/languageSelect/languageSelect.component.tsx
src/components/modals/betaReleaseAuthModal/betaReleaseAuthModal.component.tsx
src/components/modals/graphQLQueryModal/graphQLQueryModal.component.tsx
src/components/modals/graphQLQueryModal/graphQLQueryModal.test.tsx
src/components/modals/searchObjectsModal/searchObjectsModal.test.tsx
src/components/navigation/navigation/navigation.component.tsx
src/components/objectSearch/objectSearch.component.tsx
src/components/objectSearch/objectSearch.test.tsx
src/components/objectSearch/results/columnConfiguration.tsx
src/contexts/useUser.tsx
src/hooks/availability/useAvailabilityDimensionWithValues.tsx
src/hooks/localStorage/useCreds.tsx
src/hooks/localStorage/useObjectSearchTabs.tsx
src/hooks/objects/get/useGetObjectContent.tsx
src/hooks/useAccountStatus.tsx
src/hooks/useConnectedToSkylark.tsx
src/hooks/useSkylarkSchemaIntrospection.tsx
src/hooks/useUserAccount.tsx
src/interfaces/skylark/responses.ts
src/lib/utils/utils.test.ts
src/lib/utils/utils.ts
src/pages/_app.tsx
src/pages/beta/connect.tsx
src/pages/developer/graphql-editor.tsx
src/pages/import/csv.tsx

Tabbed Object Search:
- Refetch when account changes
- Move object tab logic to custom hook to make it easier to manage
Also:
- Add useLocalStorage hook for creds, move to a single LocalStorage value
- Refetch Schema when `URI` changes

feat: Local Storage changes for Credentials and Content Library Tabs

---

.github/workflows/cypress-tests.yml
cypress/e2e/contentLibrary/dragdrop.cy.ts
cypress/e2e/contentLibrary/search.cy.ts
renovate.json
src/components/availability/summary/availabilitySummary.component.tsx
src/components/availability/summary/availabilitySummary.test.tsx
src/components/panel/panelSections/panelAvailability.component.tsx
src/components/panel/panelSections/panelRelationships.component.tsx
src/components/pill/pill.component.tsx
src/hooks/useSkylarkObjectTypes.ts

- Tweak Cypress tests to improve their reliability and make Percy snapshots change less
- Increase Cypress parallel to 5
- Make Renovate bundle non-major changes into a single PR, only run on Monday
-  

fix: reduce flakiness of Cypress and Percy tests

---

.vscode/settings.json
src/__tests__/fixtures/skylark/mutations/batchDeleteObjects.json
src/__tests__/fixtures/skylark/queries/getAccountStatus/deletionBackgroundTasksInProgress.json
src/__tests__/mocks/handlers/deleteObjectHandlers.ts
src/components/account/status/accountStatus.component.tsx
src/components/account/status/accountStatus.test.tsx
src/components/contentLibrary/contentLibrary.component.tsx
src/components/inputs/textInput/textInput.component.tsx
src/components/modals/batchDeleteObjectsModal/batchDeleteObjectsModal.component.tsx
src/components/modals/batchDeleteObjectsModal/batchDeleteObjectsModal.stories.tsx
src/components/modals/batchDeleteObjectsModal/batchDeleteObjectsModal.test.tsx
src/components/modals/graphQLQueryModal/graphQLQueryModal.stories.tsx
src/components/objectSearch/bulkObjectOptions/bulkObjectOptions.component.tsx
src/components/objectSearch/objectSearch.component.tsx
src/components/objectSearch/objectSearch.test.tsx
src/components/panel/__tests__/tabs/relationships.test.tsx
src/components/panel/__tests__/utils/test-utils.ts
src/components/panel/panel.component.tsx
src/components/panel/panel.stories.tsx
src/components/panel/panelSections/panelRelationships.component.tsx
src/components/panel/panelSections/panelRelationshipsSection.component.tsx
src/components/tabs/tabs.component.tsx
src/hooks/objects/delete/useBulkDeleteObjects.tsx
src/hooks/state/usePanelObjectState.tsx
src/hooks/useAccountStatus.tsx
src/interfaces/skylark/responses.ts
src/lib/graphql/skylark/client.ts
src/lib/graphql/skylark/mutations.ts
src/pages/object/[objectType]/[uid].tsx

- Bulk Actions: When you select an object it enables the `Bulk Options` button which currently only contains `Bulk Delete`
- Bulk Delete: Delete multiple objects at once
- Improved Tab State History: when you expand a relationship and navigate to an object, the relationship will stay expanded.
https://skylarkplatform.atlassian.net/browse/SL-2886

feat: Bulk Delete & Improved Tab State History

---

src/lib/flatfile/import.ts
src/lib/graphql/skylark/dynamicMutations/objects.ts
src/lib/skylark/parsers.test.ts
src/lib/skylark/parsers.ts

- CSV importer is broken as it tries to send `external_id: null` when one isn't given. I broke this a few weeks ago when enabling sending `external_id: null` on update.

fix: null external_id in CSV importer

---

cypress/e2e/contentLibrary/search.cy.ts
cypress/e2e/contentLibrary/tabs.cy.ts
src/components/checkboxGrid/checkboxGrid.component.tsx
src/components/contentLibrary/contentLibrary.component.tsx
src/components/contentLibrary/tabbedObjectSearch/tabbedObjectSearch.test.tsx
src/components/inputs/switch/switch.component.tsx
src/components/inputs/switch/switch.stories.tsx
src/components/inputs/switch/switch.test.tsx
src/components/modals/searchObjectsModal/searchObjectsModal.component.tsx
src/components/objectSearch/objectSearch.component.tsx
src/components/objectSearch/objectSearch.test.tsx
src/components/objectSearch/results/grids/grids.tsx
src/components/objectSearch/results/grids/headers.tsx
src/components/objectSearch/results/grids/rows.tsx
src/components/objectSearch/results/objectSearchResults.component.tsx
src/components/objectSearch/search/search.component.tsx
src/components/objectSearch/search/search.stories.tsx
src/components/objectSearch/search/searchFilter/searchFilter.component.tsx
src/components/objectSearch/search/searchFilter/searchFilter.test.tsx
src/constants/localStorage.ts
src/hooks/useSkylarkObjectTypes.ts
src/lib/skylark/objects.ts

- Fixes a bug where the search filter would disappear behind the Panel making it unusable
- Fixes (hopefully) the bug where rows would become un-draggable
- Adds a new way to filter columns by sectioning the columns by Object Type
Also: 
- Tweaks the object search to remove sorting and use react-table to sort the frozen columns (slight bugfix)
https://skylarkplatform.atlassian.net/browse/SL-2821
https://skylarkplatform.atlassian.net/browse/SL-2891

bugfix: Search Filters disappears behind Panel + Column Filter by Object Type

---

src/components/objectSearch/objectSearch.component.tsx

Previous PR introduced a bug because it always set the column order.

fix: only set column order when its actually set

---

cypress/e2e/contentLibrary/panel/tabs/relationships.cy.ts
src/components/panel/__tests__/tabs/relationships.test.tsx
src/components/panel/__tests__/utils/test-utils.ts
src/components/panel/panel.stories.tsx
src/components/panel/panelSections/panelAvailability.component.tsx
src/components/panel/panelSections/panelAvailabilityDimensions.component.tsx
src/components/panel/panelSections/panelContent.component.tsx
src/components/panel/panelSections/panelContentOf.component.tsx
src/components/panel/panelSections/panelImages.component.tsx
src/components/panel/panelSections/panelMetadata.component.tsx
src/components/panel/panelSections/panelPlayback.component.tsx
src/components/panel/panelSections/panelRelationships.component.tsx
src/components/panel/panelSections/panelRelationshipsSection.component.tsx
src/components/panel/panelSections/panelSectionLayout.component.tsx
src/components/panel/panelTypography/panelTypography.component.tsx
src/hooks/objects/get/useGetObjectRelationships.ts
src/hooks/state/usePanelObjectState.tsx
src/pages/object/[objectType]/[uid].tsx
tailwind.config.js

- Refactors the Relationships Panel so that to view more on a relationship, you expand it. This change means that pagination for relationships will only happen when the user has scrolled to the end or loaded more.
https://skylarkplatform.atlassian.net/browse/SL-2916

feat: Expand/focus single relationship

---

cypress/e2e/contentLibrary/dragdrop.cy.ts
src/components/availability/summary/availabilitySummary.component.tsx
src/components/contentModel/navigation/contentModelNavigation.component.tsx
src/components/navigation/navigation/navigation.component.tsx
src/components/panel/__tests__/panel.lib.test.tsx
src/components/panel/__tests__/tabs/relationships.test.tsx
src/components/panel/panel.component.tsx
src/components/panel/panel.lib.ts
src/components/panel/panelSections/panelHeader.component.tsx
src/components/panel/panelSections/panelRelationships.component.tsx
src/components/panel/panelSections/panelRelationshipsSection.component.tsx
src/components/panel/panelSections/panelSectionLayout.component.tsx
src/hooks/objects/get/useGetObjectRelationships.ts
src/hooks/useSkylarkObjectTypes.ts
src/hooks/useSkylarkSchemaIntrospectionAsDataModelJSON.tsx
src/lib/utils/utils.test.ts
src/lib/utils/utils.ts

Builds on the ability to make a relationship focussed by using that as the target relationship when dragging.
- If none are active/focussed, work as before (add to multiple)
- If one is active, any that don't match the relationship's object type will show an error
- If two relationships share the same object type, this new method of making one active can be used to target a specific relationship - otherwise it falls back to the previous best guess method.
https://skylarkplatform.atlassian.net/browse/SL-2647

feat: when dragging into the relationships panel, use the active relationship (if any) as the target object type

---

package.json
yarn.lock

Upgrading to V4 is causing issues with Chromatic snapshots and in the future DaisyUI could be removed altogether, it isn't being used to anywhere near its full potential.

chore: upgrade daisyui to v3

---

src/components/account/status/accountStatus.component.tsx
src/hooks/useAccountStatus.tsx
src/interfaces/skylark/environment.ts
src/interfaces/skylark/responses.ts

`getActivationStatus` requires an Admin key. This change makes the useAccountStatus handle getting an error but still having the UI show as connected.
https://skylarkplatform.atlassian.net/browse/SL-2939

feat: handle permissions when editor API key is used

---

src/components/wysiwygEditor/wysiwygEditor.component.tsx
src/components/wysiwygEditor/wysiwygEditor.test.tsx

This should catch TinyMCE converting non-html strings (`this is a string`) into HTML strings: (`<p>this is a string</p>`) causing users to think they've changed something. Now the conversion will only happen when they actually edit the textbox.

feat: only call wysiwyg editor onChange when it has initialised
